from net.colors.colors import *

# ---------------- #
# COLOR ANNOTATION #
# ---------------- #
# list of colors for annotation (used in debug_hooking.py)
color_annotation = [AQUAMARINE4, BISQUE4, BLUE4, BROWN4, CADETBLUE4, CHARTREUSE4, CHOCOLATE4, CORAL4, DARKGOLDENROD4, DARKOLIVEGREEN4,
                DARKORANGE4, DARKORCHID4, DARKSEAGREEN4, DARKSLATEGRAY4, DEEPPINK4, DEEPSKYBLUE4, DODGERBLUE4, FIREBRICK4, GOLD4, GOLDENROD4,
                GREEN4, HOTPINK4, INDIANRED4, KHAKI4, LIGHTBLUE4, LIGHTCYAN4, LIGHTGOLDENROD4, LIGHTPINK4, LIGHTSALMON4, LIGHTSKYBLUE4,
                LIGHTSTEELBLUE4, MAGENTA4, MAROON4, MEDIUMORCHID4, MEDIUMPURPLE4, NAVAJOWHITE4, OLIVEDRAB4, ORANGE4, ORANGERED4, ORCHID4,
                PALEGREEN4, PALETURQUOISE4, PALEVIOLETRED4, PINK4, PLUM4, PURPLE4, RED4, ROYALBLUE4, SALMON4, SEAGREEN4,
                SIENNA4, SKYBLUE4, SLATEBLUE4, SLATEGRAY4, SPRINGGREEN3, STEELBLUE4, TAN4, THISTLE4, TOMATO4, TURQUOISE4,
                VIOLETRED4, YELLOW4,

                AQUAMARINE4, BISQUE4, BLUE4, BROWN4, CADETBLUE4, CHARTREUSE4, CHOCOLATE4, CORAL4, DARKGOLDENROD4, DARKOLIVEGREEN4,
                DARKORANGE4, DARKORCHID4, DARKSEAGREEN4, DARKSLATEGRAY4, DEEPPINK4, DEEPSKYBLUE4, DODGERBLUE4, FIREBRICK4, GOLD4, GOLDENROD4,
                GREEN4, HOTPINK4, INDIANRED4, KHAKI4, LIGHTBLUE4, LIGHTCYAN4, LIGHTGOLDENROD4, LIGHTPINK4, LIGHTSALMON4, LIGHTSKYBLUE4,
                LIGHTSTEELBLUE4, MAGENTA4, MAROON4, MEDIUMORCHID4, MEDIUMPURPLE4, NAVAJOWHITE4, OLIVEDRAB4, ORANGE4, ORANGERED4, ORCHID4,
                PALEGREEN4, PALETURQUOISE4, PALEVIOLETRED4, PINK4, PLUM4, PURPLE4, RED4, ROYALBLUE4, SALMON4, SEAGREEN4,
                SIENNA4, SKYBLUE4, SLATEBLUE4, SLATEGRAY4, SPRINGGREEN3, STEELBLUE4, TAN4, THISTLE4, TOMATO4, TURQUOISE4,
                VIOLETRED4, YELLOW4]

# ----------------------------- #
# COLOR POSITIVE GRAVITY POINTS #
# ----------------------------- #
# list of colors for positive gravity points (used in debug_hooking.py)
color_positive_gravity_points = [AQUAMARINE1, BISQUE1, BLUE, BROWN1, CADETBLUE1, CHARTREUSE1, CHOCOLATE1, CORAL1, DARKGOLDENROD1, DARKOLIVEGREEN1,
                                 DARKORANGE1, DARKORCHID1, DARKSEAGREEN1, DARKSLATEGRAY1, DEEPPINK1, DEEPSKYBLUE1, DODGERBLUE1, FIREBRICK1, GOLD1, GOLDENROD1,
                                 GREEN1, HOTPINK1, INDIANRED1, KHAKI1, LIGHTBLUE1, LIGHTCYAN1, LIGHTGOLDENROD1, LIGHTPINK1, LIGHTSALMON1, LIGHTSKYBLUE1,
                                 LIGHTSTEELBLUE1, MAGENTA, MAROON1, MEDIUMORCHID1, MEDIUMPURPLE1, NAVAJOWHITE1, OLIVEDRAB1, ORANGE1, ORANGERED1, ORCHID1,
                                 PALEGREEN1, PALETURQUOISE1, PALEVIOLETRED1, PINK1, PLUM1, PURPLE1, RED1, ROYALBLUE1, SALMON1, SEAGREEN1,
                                 SIENNA1, SKYBLUE1, SLATEBLUE1, SLATEGRAY1, SPRINGGREEN1, STEELBLUE1, TAN1, THISTLE1, TOMATO1, TURQUOISE1,
                                 VIOLETRED1, YELLOW1,

                                 AQUAMARINE1, BISQUE1, BLUE, BROWN1, CADETBLUE1, CHARTREUSE1, CHOCOLATE1, CORAL1, DARKGOLDENROD1, DARKOLIVEGREEN1,
                                 DARKORANGE1, DARKORCHID1, DARKSEAGREEN1, DARKSLATEGRAY1, DEEPPINK1, DEEPSKYBLUE1, DODGERBLUE1, FIREBRICK1, GOLD1, GOLDENROD1,
                                 GREEN1, HOTPINK1, INDIANRED1, KHAKI1, LIGHTBLUE1, LIGHTCYAN1, LIGHTGOLDENROD1, LIGHTPINK1, LIGHTSALMON1, LIGHTSKYBLUE1,
                                 LIGHTSTEELBLUE1, MAGENTA, MAROON1, MEDIUMORCHID1, MEDIUMPURPLE1, NAVAJOWHITE1, OLIVEDRAB1, ORANGE1, ORANGERED1, ORCHID1,
                                 PALEGREEN1, PALETURQUOISE1, PALEVIOLETRED1, PINK1, PLUM1, PURPLE1, RED1, ROYALBLUE1, SALMON1, SEAGREEN1,
                                 SIENNA1, SKYBLUE1, SLATEBLUE1, SLATEGRAY1, SPRINGGREEN1, STEELBLUE1, TAN1, THISTLE1, TOMATO1, TURQUOISE1,
                                 VIOLETRED1, YELLOW1]
